import React, { useState } from 'react';
import type { ImageScanMetadata } from '@repo/shared-types';

import { Modal } from '@/components/shared/Modal';
import { Button } from '@/components/shared/Button';

import { cn } from '@/lib/utils/cn';
import { useClipboard } from '@/lib/utils/useClipboard';
import type { QRAnalysisResult } from './GenerationPage';

interface ResultDisplayProps {
  images: string[];
  qrAnalysis?: QRAnalysisResult | null;
  isLoading?: boolean;
  /**
   * Server-side scan verification (plan 008), parallel to the ORIGINAL
   * `images` order (the grid renders the analyzer's reordered list, so
   * entries are looked up by original index). Absent for jobs generated by
   * container images without scan verification — the client-side analyzer
   * behavior is unchanged in that case.
   */
  imagesMetadata?: ImageScanMetadata[];
}

const ImageSkeleton = ({ className }: { className?: string }) => (
  <div className={cn('animate-pulse rounded-lg bg-hairline', className)} />
);

export const ResultDisplay: React.FC<ResultDisplayProps> = ({
  images,
  qrAnalysis,
  isLoading,
  imagesMetadata,
}) => {
  const [selectedImage, setSelectedImage] = useState<string | null>(null);
  const [downloadingIndex, setDownloadingIndex] = useState<number | null>(null);
  const [downloadedImages, setDownloadedImages] = useState<Set<number>>(new Set());
  const [loadingImages, setLoadingImages] = useState<Set<number>>(new Set());
  const { copied, copy } = useClipboard();

  const handleImageLoad = (index: number) => {
    setLoadingImages((prev) => {
      const newSet = new Set(prev);
      newSet.delete(index);
      return newSet;
    });
  };

  const handleImageLoadStart = (index: number) => {
    setLoadingImages((prev) => new Set(prev).add(index));
  };

  const handleImageClick = (imageUrl: string) => {
    setSelectedImage(imageUrl);
  };

  const handleDownload = async (imageUrl: string, index?: number) => {
    try {
      if (index !== undefined) {
        setDownloadingIndex(index);
      }

      const urlParts = imageUrl.split('/');
      const filename = urlParts[urlParts.length - 1] || `qr-code-${Date.now()}.png`;

      // `cache: 'no-store'` is required: the <img> that displays the artwork
      // fetches the same URL without CORS, and S3 caches that response with no
      // Access-Control-Allow-Origin and no `Vary: Origin` (max-age 1y). Reusing
      // that cached entry makes this cross-origin fetch fail CORS. Bypass it.
      const response = await fetch(imageUrl, { cache: 'no-store' });
      if (!response.ok) throw new Error('Failed to fetch image');

      const blob = await response.blob();

      const blobUrl = window.URL.createObjectURL(blob);

      const link = document.createElement('a');
      link.href = blobUrl;
      link.download = filename;
      document.body.appendChild(link);
      link.click();

      document.body.removeChild(link);
      window.URL.revokeObjectURL(blobUrl);

      if (index !== undefined) {
        setDownloadedImages((prev) => new Set(prev).add(index));
        setTimeout(() => {
          setDownloadingIndex(null);
        }, 500);
      }
    } catch (error) {
      console.error('Error downloading image:', error);
      alert('Failed to download image. Please try again.');
      setDownloadingIndex(null);
    }
  };

  if (isLoading) {
    return (
      <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
        {[1, 2, 3].map((i) => (
          <div
            key={i}
            className="aspect-square animate-pulse rounded-xl border-2 border-hairline bg-hairline"
          />
        ))}
      </div>
    );
  }

  if (!images || images.length === 0) {
    return (
      <div className="py-12 text-center">
        <p className="font-serif text-xl italic text-ink">No artworks yet</p>
        <p className="mt-2 text-sm text-faint">Submit a prompt to paint your QR codes.</p>
      </div>
    );
  }

  return (
    <>
      <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
        {qrAnalysis?.reorderedImages.map((imageUrl, index) => {
          const isBest = imageUrl === qrAnalysis?.bestImageUrl;
          const isImageLoading = loadingImages.has(index);

          // Server scan metadata is parallel to the original images order;
          // map the displayed (reordered) url back to its original index.
          const originalIndex = images.indexOf(imageUrl);
          const scanMeta = originalIndex >= 0 ? imagesMetadata?.[originalIndex] : undefined;
          const isServerVerified = scanMeta?.scanVerified === true;
          const scorePct =
            typeof scanMeta?.scanScore === 'number' ? Math.round(scanMeta.scanScore * 100) : null;
          const isDownloading = downloadingIndex === index;
          const isDownloaded = downloadedImages.has(index);

          return (
            <div key={`${imageUrl}-${index}`} className="flex flex-col">
              <div
                className={cn(
                  'relative rounded-xl border-2 border-ink bg-paper p-2.5',
                  isBest ? 'shadow-hero' : 'shadow-card'
                )}
              >
                {isBest && (
                  <span className="absolute -right-3 -top-3 z-20 rotate-6 rounded-full border-2 border-ink bg-blue px-3 py-1 text-[10px] font-bold uppercase tracking-[0.1em] text-paper">
                    {isServerVerified
                      ? `Top · Verified${scorePct != null ? ` ${scorePct}%` : ''}`
                      : 'Top'}
                  </span>
                )}

                <div className="relative aspect-square overflow-hidden rounded-lg">
                  {isImageLoading && (
                    <div className="absolute inset-0 z-10">
                      <ImageSkeleton className="h-full w-full" />
                    </div>
                  )}

                  <img
                    src={imageUrl}
                    alt={`Generated QR Code ${index + 1}`}
                    className={cn(
                      'h-full w-full cursor-pointer object-cover transition-opacity duration-300',
                      isImageLoading ? 'opacity-0' : 'opacity-100'
                    )}
                    loading={index === 0 ? 'eager' : 'lazy'}
                    onLoadStart={() => handleImageLoadStart(index)}
                    onLoad={() => handleImageLoad(index)}
                    onError={() => handleImageLoad(index)}
                    onClick={() => handleImageClick(imageUrl)}
                  />
                </div>
              </div>

              <p
                className={cn(
                  'mt-2.5 text-center text-[12px] font-semibold',
                  isServerVerified ? 'text-green' : 'text-faint'
                )}
              >
                № {index + 1} · {isServerVerified ? 'scans ✓' : 'test first'}
              </p>

              <div className="mt-2 flex items-center justify-center gap-2">
                <button
                  onClick={() => handleImageClick(imageUrl)}
                  className="rounded-full border-2 border-ink bg-paper px-4 py-1 text-[12px] font-semibold text-ink transition-colors hover:bg-yellow"
                >
                  View
                </button>
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    handleDownload(imageUrl, index);
                  }}
                  disabled={isDownloading}
                  className={cn(
                    'inline-flex items-center gap-1.5 rounded-full border-2 border-ink px-4 py-1 text-[12px] font-semibold transition-colors',
                    isDownloaded ? 'bg-green text-paper' : 'bg-paper text-ink hover:bg-yellow'
                  )}
                  title="Download QR code"
                >
                  {isDownloading ? (
                    <span
                      className="h-3 w-3 animate-spin border-2 border-current border-t-transparent"
                      aria-hidden="true"
                    />
                  ) : isDownloaded ? (
                    'Saved ✓'
                  ) : (
                    'Save'
                  )}
                </button>
              </div>
            </div>
          );
        })}
      </div>

      <Modal
        isOpen={!!selectedImage}
        onClose={() => setSelectedImage(null)}
        title="Your artwork"
        size="lg"
      >
        {selectedImage && (
          <div className="space-y-5">
            <div className="flex justify-center">
              <div className="w-full max-w-sm rounded-xl border-2 border-ink bg-paper p-3 shadow-card">
                <img
                  src={selectedImage}
                  alt="Generated QR Code"
                  className="h-auto w-full rounded-lg"
                  loading="eager"
                />
              </div>
            </div>

            <p className="text-center font-serif text-[15px] italic text-muted">
              Test this code with your phone before you print it.
            </p>

            <div className="flex justify-center gap-3">
              <Button variant="primary" size="lg" onClick={() => handleDownload(selectedImage)}>
                Download <span className="text-yellow">↓</span>
              </Button>
              <Button variant="outline" size="lg" onClick={() => copy(selectedImage)}>
                {copied ? 'Copied' : 'Copy link'}
              </Button>
            </div>

            <div className="rounded-xl border-2 border-dashed border-ink bg-paper p-4">
              <p className="mb-2 text-[11px] font-bold uppercase tracking-[0.12em] text-ink">
                Before printing
              </p>
              <div className="space-y-1.5 text-sm text-muted">
                <p>
                  <span className="mr-1.5 font-serif italic text-blue">i.</span>
                  Test with your phone camera first.
                </p>
                <p>
                  <span className="mr-1.5 font-serif italic text-red">ii.</span>
                  Keep good contrast when printing.
                </p>
                <p>
                  <span className="mr-1.5 font-serif italic text-yellow">iii.</span>
                  Print at 2cm × 2cm or larger.
                </p>
              </div>
            </div>
          </div>
        )}
      </Modal>
    </>
  );
};
