import type {
  SupportedPipeline,
  StylePreset,
  ScanStrictness,
} from "@repo/qr-constants";

import type {
  BaseEntity,
  JobStatus,
  SamplerType,
  ModelType,
  ErrorDetails,
} from "../common";

// QR generation request parameters
export interface QRGenerationRequest {
  // Core parameters
  prompt: string;
  baseQrCode: string[];
  numImagesPerPrompt?: number;

  // Generation parameters
  negativePrompt?: string;
  numInferenceSteps?: number;
  controlnetConditioningScale?: [number, number];
  controlGuidanceStart?: [number, number];
  controlGuidanceEnd?: [number, number];

  // Image parameters
  height?: number;
  width?: number;

  // Model parameters
  sampler?: SamplerType;
  guidanceScale?: number;
  model?: ModelType;
  seed?: number;

  // Advanced parameters
  guessMode?: boolean;
  promptEnhancement?: boolean;

  // Environment routing (staging vs production)
  environment?: 'production' | 'staging';

  // v2 pipeline (plan 008) — all optional; when absent the container's own
  // default ("v1") rules, so absent must stay absent end-to-end
  pipeline?: SupportedPipeline;
  qrContent?: string;
  stylePreset?: StylePreset;
  scanStrictness?: ScanStrictness;
}

export interface GenerationDetail {
  index: number;
  url: string;
  scales: [number, number];
  description: string;
  usesAlternativeScales: boolean;
}

export interface GenerationPlan {
  totalGenerations: number;
  uniqueUrls: number;
  userScaleCount: number;
  alternativeScaleCount: number;
  details: GenerationDetail[];
}

/**
 * Per-image scan verification metadata (plan 008). Emitted by the container
 * as a top-level `images_metadata` list parallel to `images`; mapped to
 * camelCase by JobManager (same convention as processingTimeSeconds /
 * generationPlan). `null` means "not measured" (e.g. v1 jobs on an old
 * image), distinct from a failed verification.
 */
export interface ImageScanMetadata {
  scanVerified: boolean | null;
  scanScore: number | null;
  decodersPassed: string[];
  repairStageUsed: string | null;
  seed?: number;
}

export interface QRGenerationResult {
  images: string[];
  image_urls?: string[];
  outputPaths: string[];
  numImagesGenerated: number;
  processingTimeSeconds?: number;
  generationPlan?: GenerationPlan;
  generations?: GenerationDetail[];
  inputQrUrls?: string[];
  qrSource?: string;
  s3Bucket?: string;
  // Parallel to `images`; absent for jobs generated by container images that
  // predate scan verification
  imagesMetadata?: ImageScanMetadata[];
}

export interface QRJob extends BaseEntity {
  // Job status and progress
  status: JobStatus;
  progress?: number;
  message?: string;

  // Timing information
  startedAt?: string;
  completedAt?: string;
  failedAt?: string;
  estimatedTimeRemaining?: string;

  // Request data (what the user submitted)
  requestData: QRGenerationRequest;

  // Result data (when completed)
  result?: QRGenerationResult;

  // Error details (when failed)
  error?: ErrorDetails;
}

export interface QRJobCreateResponse {
  jobId: string;
  status: JobStatus;
  message: string;
  estimatedTime?: string;
  statusUrl: string;
}

export interface QRJobStatusResponse {
  jobId: string;
  status: JobStatus;
  progress?: number;
  message?: string;
  createdAt: string;
  startedAt?: string;
  completedAt?: string;
  failedAt?: string;
  estimatedTimeRemaining?: string;

  // Original prompt from the request
  prompt?: string;

  // Result when completed
  result?: QRGenerationResult;

  // Error when failed
  error?: ErrorDetails;
}

export interface QRJobCancelResponse {
  jobId: string;
  status: JobStatus;
  message: string;
  cancelledAt?: string;
}

export interface ControlNetServiceResponse {
  images?: string[];
  image_urls?: string[];
  output_paths?: string[];
  num_images_generated?: number;
  processing_time_seconds?: number;
  generation_plan?: Record<string, any>;
  generations?: any[];
  input_qr_urls?: string[];
  qr_source?: string;
  s3_bucket?: string;
  // Raw (snake_case) per-image scan metadata from the container result JSON
  images_metadata?: Array<Record<string, any>>;
}

export interface ControlNetServiceError {
  error: string;
  traceback?: string;
}
